name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4.1.6
    - name: Set up JDK 11
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2

    - name: Build with Gradle Wrapper
      run: ./gradlew build --scan
